# Copyright (c) Robert Bosch GmbH
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: ConsistencyCheck

on:
 push:

env:
  ModelName: PWC
  ModelExtension: eapx

jobs:
  ConsistencyCheck:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          fetch-depth: 0
                      
      - name: GetLTA
        uses: LieberLieber/setup-LemonTree.Automation@v0.6
        id: GetLTA
        with:
          License: ${{secrets.LTALICENSE}}

      - name: ConsistencyCheck
        run: |
          &"${{steps.GetLTA.outputs.LemonTreeAutomationExecutable}}" ConsistencyCheck --Model ${{env.ModelName}}.${{env.ModelExtension}}
 
     
    