# Copyright (c) Robert Bosch GmbH
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: Publish Components

on:
 push:
  branches:
      - main
env:
  ModelName: PWC
  ModelExtension: eapx
  ReviewSessionURL: https://nexus.lieberlieber.com/repository/lemontree-component/
  LemonTreeAutomationExecutable: C:\Program Files\LieberLieber\LemonTree.Automation\LemonTree.Automation.exe
  ComponentModelShortCut: C:\tools\Shortcuts\Shortcut_LL_TEST_COMPONENTS.eap

jobs:
  PublishComponents:
    defaults:
      run:
        shell: pwsh
    runs-on: [self-hosted, lemontree]
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          fetch-depth: 0
                      

      - name: Publish LemonTree Components
        run: |
          &"${{env.LemonTreeAutomationExecutable}}" publish --Model ${{env.ModelName}}.${{env.ModelExtension}} --PackageDirectory ".\\" --All

      - name: Import LemonTree Components on MSSQL Repository 
        run: |
          &"${{env.LemonTreeAutomationExecutable}}" import --Model ${{env.ComponentModelShortCut}} --Components "*.mpms"

      - name: Archive Session Files
        uses: actions/upload-artifact@v3
        with:
          name: Model Components
          path: "*.mpms"
          retention-days: 5

      - name: Upload LemonTree Components to Nexus
        run: |
          $files = Get-ChildItem *.mpms
          foreach ($file in $files) 
          {
            $sfName =  $file.Name
            $sfNameUri = [uri]::EscapeDataString($sfName)
            $targetUrl = "${{env.ReviewSessionURL}}$sfNameUri"
            echo "Uploading $sfName to Nexus: $targetUrl"
            while (Test-Path Alias:curl) {Remove-Item Alias:curl} #remove the alias binding from curl to Invoke-WebRequest
            curl "-u${{secrets.NEXUSAUTHENTICATION}}" -T ".\$sfName" "$targetUrl"
          }
         
   

    